In [19]:
# 연습문제 1
import numpy as np

arr4 = np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
print(arr4)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [20]:
# 연습문제 2
print(arr4[[0,1],[1,2]])


[20 60]


In [18]:
# 연습문제 3
print(arr4[0:2,1:3])

[[20 30]
 [50 60]]
